---
- name: "TEST API"
  hosts: localhost
  gather_facts: no

  tasks:   

    - name: "gitea - post"
      uri:
        url: http://192.168.1.153:3000
        method: POST
        body_format: form-urlencoded
        body:
          db_type: postgres
          db_host: gitea-postgres
          db_user: gitea
          db_passwd: gitea
          db_name: gitea
          ssl_mode: disable
          # db_schema: ''
          charset: utf8
          db_path: /data/gitea/gitea.db
          app_name: 'Gitea:+Git+with+a+cup+of+tea'
          repo_root_path: /data/git/repositories
          lfs_root_path: /data/git/lfs
          run_user: git
          domain: gitea.tethryus.ro
          ssh_port: 222
          http_port: '3000'
          app_url: 'https://gitea.tethryus.ro/'
          log_root_path: '/data/gitea/log'
          # smtp_host: ''
          # smtp_from: ''
          # smtp_user: ''
          # smtp_passwd: ''
          enable_federated_avatar: on
          enable_open_id_sign_in: on
          enable_open_id_sign_up: on
          default_allow_create_organization: on
          default_enable_timetracking: on
          no_reply_address: 'noreply.gitea.tethryus.ro'
          password_algorithm: 'pbkdf2'
          # admin_name: ''
          # admin_passwd: ''
          # admin_confirm_passwd: ''
          # admin_email: ''
      register: _response
