- name: Copy service docker-compose file
  include_tasks: ../tasks/ansible.builtin.template_compose.yml
  vars:
    service: watchtower

- name: Start service
  include_tasks: ../tasks/compose_up.yml
  vars:
    service: watchtower
