- name: Get Radarr download clients
  uri:
    url: "{{ radarr_api_url }}/downloadclient?apiKey={{ radarr_api_key }}"
    method: GET
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404 

- name: Check if download client {{ radarr_dc }} configured
  set_fact:
    _radarr_dc_not_configured: "{{ _response.json | json_query(q) | length() == 0 }}"
  vars:
    q: "[?name == `{{ radarr_dc }}`]"

- name: Set download client {{ radarr_dc }} variables
  set_fact:
    radarr_dc_host: "{{ radarr_dc_host | default(radarr_dc) }}"
    radarr_dc_port: "{{ radarr_dc_port | default('8082' if 'qbittorrent' in radarr_dc else '9091') }}"
    radarr_dc_use_ssl: "{{ radarr_dc_use_ssl | default(true if radarr_dc_port is defined and radarr_dc_port == 443 else false) }}"
    radarr_dc_username: "{{ radarr_dc_username | default('') }}"
    radarr_dc_password: "{{ radarr_dc_password | default('') }}"

- name: Set common download client fields
  set_fact:
    _dc_fields:
      - name: host
        value: "{{ radarr_dc_host }}"
      - name: port
        value: "{{ radarr_dc_port }}"
      - name: useSsl
        value: "{{ radarr_dc_use_ssl }}"
      - name: urlBase
        value: "{{ '' if 'qbittorrent' in radarr_dc else '/transmission/' }}"
      - name: username
        value: "{{ radarr_dc_username }}"
      - name: password
        value: "{{ radarr_dc_password }}"
      - name: movieCategory
        value: "{{ radarr_dc_category | default('movies') }}"
      - name: recentMoviePriority
        value: 0
      - name: olderMoviePriority
        value: 0

- name: Set additional fields for qbittorrent
  set_fact: 
    _dc_fields: "{{ _dc_fields + additional_fields }}"
  vars:
    additional_fields:
      - name: movieImportedCategory
      - name: recentMoviePriority
        value: 0
      - name: olderMoviePriority
        value: 0
      - name: initialState
        value: 0

- name: Set additional fields for transmission
  set_fact: 
    _dc_fields: "{{ _dc_fields + additional_fields }}"
  vars:
    additional_fields:
      - name: movieDirectory
      - name: addPaused
        value: false

- name: Add qBittorrent download client if not configured
  uri:
    url: "{{ radarr_api_url }}/downloadclient?apiKey={{ radarr_api_key }}"
    method: POST
    body_format: json
    body:
      enable: true
      protocol: torrent
      priority: 1
      removeCompletedDownloads: "{{ radarr_dc_remove_completed_downloads | default(true) }}"
      removeFailedDownloads: true
      name: "{{ radarr_dc }}"
      fields: "{{ _dc_fields }}"
      implementationName: "{{ 'qBittorrent' if 'qbittorrent' in radarr_dc else 'Transmission' }}"
      implementation: "{{ 'QBittorrent' if 'qbittorrent' in radarr_dc else 'Transmission' }}"
      configContract: "{{ 'QBittorrentSettings' if 'qbittorrent' in radarr_dc else 'TransmissionSettings' }}"
      infoLink: 'https://wiki.servarr.com/radarr/supported#{{ radarr_dc }}'
      tags: []
    status_code: 201
  when: _radarr_dc_not_configured
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404 

- name: Default remote mapping
  set_fact:
    radarr_dc_mapping: "{{ sonarr_dc_mapping | default('/downloads:/data/downloads') }}"

- name: Add remote mapping for download client {{ radarr_dc }}
  uri:
    url: "{{ radarr_api_url }}/remotepathmapping?apiKey={{ radarr_api_key }}"
    method: POST
    body_format: json
    body:
      host: "{{ radarr_dc }}"
      remotePath: "{{ radarr_dc_mapping.split(':')[0] }}"
      localPath: "{{ radarr_dc_mapping.split(':')[1] }}"
    status_code: 201
  when: _radarr_dc_not_configured
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404 
