- name: Create CIFS/SMB volume {{ volume.name }}
  community.docker.docker_volume:
    name: "{{ volume.name }}"
    driver: local
    driver_options:
      type: cifs
      o: "username={{ volume.user }},password={{ volume.password }},{{ volume.options | default('file_mode=0777,dir_mode=0777,rw,noserverino,uid=99,gid=100') }}"
      device: "//{{ volume.host }}/{{ volume.device }}"
