- name: Check if file exists
  stat:
    path: "{{ project_dir }}/{{ service }}/{{ file }}"
  register: _stat

- name: Create file in service folder if not exists
  file:
    path: "{{ project_dir }}/{{ service }}/{{ file }}"
    state: touch
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0644'
  when: not _stat.stat.exists
