---
- name: Add Nvidia Docker GPG Key
  ansible.builtin.shell: 'curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add -'
  become: true
  changed_when: true

- name: Add Nvidia Docker Repository
  ansible.builtin.shell: 'curl -s -L https://nvidia.github.io/nvidia-docker/{{ ansible_distribution |lower }} \
    {{ ansible_distribution_version }}/nvidia-docker.list \
    | sudo tee /etc/ansible.builtin.apt/sources.list.d/nvidia-docker.list'
  become: true
  changed_when: true

- name: Update cache and install nvidia-container-toolkit
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg: nvidia-container-toolkit
  register: _result

- name: Restart docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: restarted
  when: _result.changed
