- name: Check if task {{ task }} exists for service {{ service }}
  ansible.builtin.stat:
    path: ../services/{{ service }}/{{ task }}.yml
  become: true
  register: _response
  delegate_to: localhost

- name: Include task {{ task }} for service {{ service }}
  include_tasks: ../services/{{ service }}/{{ task }}.yml
  when: _response.stat.exists is defined and _response.stat.exists
