- name: Check if vars file {{ file | default('vars') }} exists for {{ service }}
  local_action: stat path=../services/{{ service }}/{{ file | default('vars') }}.yml
  become: false
  register: _response

- name: Include vars file {{ file | default('vars') }} for service {{ service }}
  include_vars: ../services/{{ service }}/{{ file | default('vars') }}.yml
  when: _response.stat.exists is defined and _response.stat.exists
