- name: Create project folder
  ansible.builtin.file:
    path: "{{ project_dir }}"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0755'
