- name: Ensure path to service folder for {{ service }}
  ansible.builtin.file:
    path: "{{ project_dir }}/{{ service }}"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0755'

- name: Template compose file for {{ service }}
  ansible.builtin.template:
    src: ../services/{{ service }}/compose.yml.j2
    dest: "{{ project_dir }}/{{ service }}/compose.yml"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0644'
  register: _compose_file
