- name: Check for updates
  become: true
  apt:
    update_cache: yes
  when: ansible_facts.pkg_mgr == 'apt'

- name: Update host with apt
  become: true
  apt:
    autoclean: yes
    autoremove: yes
    upgrade: dist
  register: _response
  when: ansible_facts.pkg_mgr == 'apt'

- name: Update host with dnf
  become: true
  dnf:
    name: "*"
    state: latest
  register: _response
  when: ansible_facts.pkg_mgr == 'dnf'

- name: Check if reboot needed
  set_fact:
    reboot_needed: "{{ _response.changed }}"

- name: Install packages with apt
  become: true
  apt:
    pkg: "{{ packages }}"
  register: _response
  when: ansible_facts.pkg_mgr == 'apt' and packages

- name: Install packages with dnf
  become: true
  dnf:
    name: "{{ packages }}"
    state: latest
  register: _response
  when: ansible_facts.pkg_mgr == 'dnf' and packages

- name: Check if reboot needed
  set_fact:
    reboot_needed: "{{ _response.changed }}"
  when: not reboot_needed

- name: Check for SELinux config file
  stat:
    path: /etc/selinux/config
  register: _result

- name: Disable SELinux if enabled
  become: true
  lineinfile:
    create: yes
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: "SELINUX=disabled"
  register: _result
  when: _result.stat.exists

- name: Check if reboot needed
  set_fact:
    reboot_needed: "{{ _result.changed }}"
  when: not reboot_needed
