- name: Check for updates
  become: true
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    upgrade: dist
  register: _response

- name: Check if reboot needed
  set_fact:
    reboot_needed: "{{ _response.changed }}"

- name: Install packages with apt
  become: true
  apt:
    pkg: "{{ packages }}"
  when: packages is defined
  register: _response

- name: Check if reboot needed
  set_fact:
    reboot_needed: "{{ _response.changed }}"
  when: not reboot_needed
