- name: Check for updates
  become: yes
  apt:
    update_cache: yes

- name: Update host
  become: yes
  apt:
    autoclean: yes
    autoremove: yes
    upgrade: dist
  register: _response

- name: Check if reboot needed
  set_fact:
    reboot_needed: "{{ _response.changed }}"

- name: Install packages
  become: yes
  apt:
    pkg: "{{ packages }}"
  when: packages
  register: _response

- name: Check if reboot needed
  set_fact:
    reboot_needed: "{{ _response.changed }}"
  when: not reboot_needed
