- name: Check for updates
  become: true
  ansible.builtin.apt:
    update_cache: true
    autoclean: true
    autoremove: true
    upgrade: dist
  register: _response

- name: Check if reboot needed
  ansible.builtin.set_fact:
    reboot_needed: "{{ _response.changed }}"

- name: Install packages with apt
  become: true
  ansible.builtin.apt:
    pkg: "{{ packages }}"
  when: packages is defined
  register: _response

- name: Check if reboot needed
  ansible.builtin.set_fact:
    reboot_needed: "{{ _response.changed }}"
  when: not reboot_needed
