---
- name: Configure DNS settings
  ansible.builtin.uri:
    url: "{{ adguard_api }}/dns_config"
    method: POST
    body_format: json
    headers:
      Cookie: "{{ adguard_cookie }}"
    body: >
      {
        "upstream_dns": {{ adguard_upstream_dns | default(adguard_default_dns) }},
        "bootstrap_dns": {{ adguard_bootstrap_dns | default(adguard_default_bootstrap) }},
        "ratelimit": {{ adguard_ratelimit | default(adguard_default_ratelimit) }},
        "cache_size": {{ adguard_cache_size_mb | default(adguard_default_cache_size_mb) * 1024 * 1024 }}
      }
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 or _response.status == 404
