---
- name: Get existing filters
  ansible.builtin.uri:
    url: "{{ adguard_api }}/filtering/status"
    method: GET
    body_format: json
    headers:
      Cookie: "{{ adguard_cookie }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 or _response.status == 404

- name: Save existing filters
  ansible.builtin.set_fact:
    adguard_existing_filters: "{{ adguard_existing_filters | default([]) + [{'name': item.name, 'url': item.url}] }}"
  with_items: "{{ _response.json.filters }}"

- name: Default filters
  ansible.builtin.set_fact:
    adguard_filters: "{{ adguard_filters | default(adguard_default_filters) }}"

- name: Remove filters
  ansible.builtin.uri:
    url: "{{ adguard_api }}/filtering/remove_url"
    method: POST
    body_format: json
    headers:
      Cookie: "{{ adguard_cookie }}"
    body: "{{ item }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 or _response.status == 404
  with_items: "{{ adguard_existing_filters | difference(adguard_filters) }}"

- name: Add filters
  ansible.builtin.uri:
    url: "{{ adguard_api }}/filtering/add_url"
    method: POST
    body_format: json
    headers:
      Cookie: "{{ adguard_cookie }}"
    body: "{{ item }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 or _response.status == 404
  with_items: "{{ adguard_filters | difference(adguard_existing_filters) }}"
