- name: Get existing rewrites
  uri:
    url: "http://localhost:3000/control/rewrite/list"
    method: GET
    body_format: json
    headers:
      Cookie: "{{ adguard_cookie }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 or _response.status == 404

- name: Save existing rewrites
  set_fact:
    adguard_existing_rewrites: "{{ _response.json }}"

- name: Build new list of rewrites
  set_fact:
    adguard_updated_rewrites: "{{ adguard_updated_rewrites | default([]) + [{'domain': rewrite.split('|')[0], 'answer': rewrite.split('|')[1]}] }}"
  with_items: "{{ adguard_rewrites | default([]) }}"
  loop_control:
    loop_var: rewrite

- name: Remove rewrites
  uri:
    url: "http://localhost:3000/control/rewrite/delete"
    method: POST
    body_format: json
    headers:
      Cookie: "{{ adguard_cookie }}"
    body: "{{ item }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 or _response.status == 404
  with_items: "{{ adguard_existing_rewrites | difference(adguard_updated_rewrites) }}"

- name: Add rewrites
  uri:
    url: "http://localhost:3000/control/rewrite/add"
    method: POST
    body_format: json
    headers:
      Cookie: "{{ adguard_cookie }}"
    body: "{{ item }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 or _response.status == 404
  with_items: "{{ adguard_updated_rewrites | difference(adguard_existing_rewrites) }}"
