---
- name: Check for existing admin user
  ansible.builtin.uri:
    method: GET
    url: "{{ portainer_api }}/users/admin/check"
    status_code: [204, 404]
  register: admin_check_response
  retries: 10
  delay: 10
  until: admin_check_response.status != -1

- name: Initialize admin user
  uri:
    method: POST
    url: "{{ portainer_api }}/users/admin/init"
    body_format: json
    body:
      username: "{{ portainer_user }}"
      password: "{{ portainer_password }}"
    status_code: 200
  when: admin_check_response.status != 204
  register: admin_init_response
  retries: 10
  delay: 10
  until: admin_init_response.status != -1
