---
- name: Include host specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files: [ "{{ inventory_hostname }}.yml" ]
      skip: true

- name: Create directory structure
  ansible.builtin.import_role: name=common tasks_from=service_dir_structure
  vars:
    subdirs:
      - diun
      - diun/data

- name: Template diun.yml file
  ansible.builtin.template:
    src: diun.yml.j2
    dest: "{{ project_dir }}/diun/diun.yml"
    owner: "{{ ansible_facts.user_uid }}"
    group: "{{ ansible_facts.user_gid }}"
    mode: 0600

- name: Template compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ project_dir }}/diun/compose.yml"
    owner: "{{ ansible_facts.user_uid }}"
    group: "{{ ansible_facts.user_gid }}"
    mode: 0644

- name: Setup docker network {{ diun_network }}
  community.docker.docker_network:
    name: "{{ diun_network }}"

- name: Start service using docker compose
  community.docker.docker_compose:
    project_name: diun
    project_src: "{{ project_dir }}/diun"
    pull: true
    remove_orphans: true
