---
- name: Allow IPv4 forwarding
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: true

- name: Allow IPv6 forwarding
  become: true
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    sysctl_set: true
