---
- name: Check if GPG key exists
  ansible.builtin.stat:
    path: /usr/share/keyrings/tailscale-archive-keyring.gpg
  register: gpgkey_stat

- name: Get GPG signing key
  become: true
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/{{ ansible_facts.distribution | lower }}/{{ ansible_facts.distribution_release | lower }}.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    owner: root
    group: root
    mode: 0644
  when: not gpgkey_stat.stat.exists

- name: Check if sources list exists
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/tailscale.list
  register: aptlist_stat

- name: Get Tailscale sources list
  become: true
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/{{ ansible_facts.distribution | lower }}/{{ ansible_facts.distribution_release | lower }}.tailscale-keyring.list
    dest: /etc/apt/sources.list.d/tailscale.list
    owner: root
    group: root
    mode: 0644
  when: not aptlist_stat.stat.exists

- name: Install tailscale
  become: true
  ansible.builtin.apt:
    name: tailscale
    update_cache: true
