---
- name: Include host specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files: [ "{{ inventory_hostname }}.yml" ]
      skip: true

- ansible.builtin.import_tasks: enable_ip_forwarding.yml
- ansible.builtin.include_tasks: install_tailscale_{{ ansible_facts.os_family | lower }}.yml
- ansible.builtin.import_tasks: authenticate.yml
- ansible.builtin.import_tasks: configure.yml
