- name: Set Readarr API URL
  ansible.builtin.set_fact:
    readarr_api_url: "http://localhost:8787/api/v1"

- name: Get Readarr API Key
  include_tasks: tasks/api_key.yml

- name: Set rootfolder
  include_tasks: tasks/rootfolder.yml

- name: Configure Jackett indexers
  include_tasks: tasks/indexers.yml
  vars:
    indexer: "{{ i }}"
  with_items: "{{ readarr_indexers }}"
  loop_control:
    loop_var: i
  when: '"jackett" in services'

- name: Configure qBittorrent as download client
  include_tasks: tasks/download_client.yml
  when: readarr_dc is defined
