- name: Create folder for ACME data
  include_tasks: ../tasks/create_service_dir.yml
  vars:
    service: traefik
    dir: acme-data
  when: traefik_acme

- name: Copy service docker-compose file
  include_tasks: ../tasks/template_compose.yml
  vars:
    service: traefik

- name: Start service
  include_tasks: ../tasks/compose_up.yml
  vars:
    service: traefik