- name: Setup portainer api variable
  set_fact:
    portainer_api: "http://{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}:9000/api"

- name: Configure Portainer admin user
  include_tasks: tasks/configure_admin_user.yml

- name: Authenticate with Portainer
  include_tasks: tasks/auth_admin_user.yml

- name: Set dark mode for admin user
  include_tasks: tasks/enable_dark_mode.yml
  when: portainer_enable_dark_mode