- name: Setup portainer api variable
  set_fact:
    portainer_api: "http://localhost:9000/api"

- name: Configure Portainer admin user
  include_tasks: tasks/configure_admin_user.yml

- name: Authenticate with Portainer
  include_tasks: tasks/auth_admin_user.yml

- name: Set dark mode for admin user
  include_tasks: tasks/enable_dark_mode.yml
  when: portainer_enable_dark_mode is not defined or portainer_enable_dark_mode is true

- name: Configure additional agents
  include_tasks: tasks/configure_agent.yml
  vars:
    agent: "{{ i }}"
  with_items: "{{ portainer_agents }}"
  when: portainer_agents
  loop_control:
    loop_var: i
