---
- name: Include host specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files: [ "{{ ansible_hostname }}.yml" ]
      skip: true

- name: Create directory structure
  ansible.builtin.import_role: name=common tasks_from=service_dir_structure
  vars:
    subdirs:
      - sonarr
      - sonarr/config

- name: Ensure sonarr data dir exists
  when: sonarr_data_storage == "path"
  ansible.builtin.file:
    path: "{{ sonarr_data_path }}"
    state: directory
    owner: "{{ ansible_facts.user_uid }}"
    group: "{{ ansible_facts.user_gid }}"
    mode: 0700

- name: Template compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ project_dir }}/sonarr/compose.yml"
    owner: "{{ ansible_facts.user_uid }}"
    group: "{{ ansible_facts.user_gid }}"
    mode: 0600

- name: Setup docker network {{ sonarr_network }}
  community.docker.docker_network:
    name: "{{ sonarr_network }}"

- name: Start service using docker compose
  community.docker.docker_compose:
    project_name: sonarr
    project_src: "{{ project_dir }}/sonarr"
    pull: true
    remove_orphans: true

- name: Configure sonarr
  vars:
    sonarr_api: "https://sonarr.{{ domain }}/api/v3"
  block:
    - ansible.builtin.import_tasks: get_api_key.yml
    - ansible.builtin.import_tasks: set_root_path.yml
    - ansible.builtin.import_tasks: set_download_client.yml
    