- name: Configure DNS settings
  ansible.builtin.uri:
    url: "{{ adguard_api }}/dns_config"
    method: POST
    body_format: json
    headers:
      Cookie: "{{ adguard_cookie }}"
    body: >-
      {
        "upstream_dns": {{ adguard_dns }},
        "bootstrap_dns": {{ adguard_bootstrap }},
        "ratelimit": {{ adguard_ratelimit }},
        "cache_size": {{ adguard_cache_size_mb * 1024 * 1024 }}
      }
    status_code: 200
  register: dns_settings_response
  retries: 10
  delay: 10
  until: dns_settings_response.status > 0 or dns_settings_response.status == 404
