- name: Configure DNS settings
  uri:
    url: "http://localhost:3000/control/dns_config"
    method: POST
    body_format: json
    headers:
      Cookie: "{{ adguard_cookie }}"
    body: >-
      {
        "upstream_dns": {{ adguard_dns }},
        "bootstrap_dns": {{ adguard_bootstrap }},
        "ratelimit": {{ adguard_ratelimit }},
        "cache_size": {{ adguard_cache_size_mb * 1024 * 1024 }}
      }
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 or _response.status == 404
