- name: Initialize Adguard
  ansible.builtin.uri:
    url: "{{ adguard_api }}/install/configure"
    method: POST
    body_format: json
    body:
      username: "{{ adguard_user }}"
      password: "{{ adguard_pass }}"
      web:
        ip: 0.0.0.0
        port: 3000
        status: ""
        can_autofix: false
      dns:
        ip: 0.0.0.0
        port: 53
        status: ""
        can_autofix: false
    status_code: 200, 403
  register: configure_response
  retries: 10
  delay: 10
  until: configure_response.status > 0 or configure_response.status == 404

- name: Login with Adguard
  ansible.builtin.uri:
    url: "{{ adguard_api }}/login"
    method: POST
    body_format: json
    body:
      name: "{{ adguard_user }}"
      password: "{{ adguard_pass }}"
    status_code: 200
  register: auth_response
  retries: 10
  delay: 10
  until: auth_response.status > 0 or auth_response.status == 404

- name: Save Adguard cookie
  ansible.builtin.set_fact:
    adguard_cookie: "agh_session={{ auth_response.cookies.agh_session }}"
