- name: Get existing filters
  ansible.builtin.uri:
    url: "{{ adguard_api }}/filtering/status"
    method: GET
    headers:
      Accept-Encoding: gzip
      Cookie: "{{ adguard_cookie }}"
    status_code: 200
  register: get_filters_response
  retries: 10
  delay: 10
  until: get_filters_response.status > 0 or get_filters_response.status == 404

- name: Update filters
  vars:
    existing_filters: "[{% for filter in get_filters_response.json.filters %}\
      {'name': '{{ filter.name }}', 'url': '{{ filter.url }}'},
      {% endfor %}]"
  block:
    - name: Remove filters
      ansible.builtin.uri:
        url: "{{ adguard_api }}/filtering/remove_url"
        method: POST
        body_format: json
        headers:
          Cookie: "{{ adguard_cookie }}"
        body: "{{ item }}"
        status_code: 200
      register: remove_filter_response
      retries: 10
      delay: 10
      until: remove_filter_response.status > 0 or remove_filter_response.status == 404
      with_items: "{{ existing_filters | difference(adguard_filters) }}"

    - name: Add filters
      ansible.builtin.uri:
        url: "{{ adguard_api }}/filtering/add_url"
        method: POST
        body_format: json
        headers:
          Cookie: "{{ adguard_cookie }}"
        body: "{{ item }}"
        status_code: 200
      register: add_filter_response
      retries: 10
      delay: 10
      until: add_filter_response.status > 0 or add_filter_response.status == 404
      with_items: "{{ adguard_filters | difference(existing_filters) }}"
