- name: Create folder for ansible.builtin.template
  include_tasks: ../tasks/create_service_dir.yml
  vars:
    service: ansible.builtin.template
    dir: data

- name: Create docker volume for ansible.builtin.template
  include_tasks: ../tasks/local_volume.yml
  vars:
    volume:
      name: ansible.builtin.template-data
      type: local

- name: Copy service docker-compose file
  include_tasks: ../tasks/ansible.builtin.template_compose.yml
  vars:
    service: ansible.builtin.template

- name: Start service
  include_tasks: ../tasks/compose_up.yml
  vars:
    service: ansible.builtin.template
