- name: Get Sonarr download clients
  ansible.builtin.uri:
    url: "{{ sonarr_api_url }}/downloadclient?apiKey={{ sonarr_api_key }}"
    method: GET
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404

- name: Check if download client {{ sonarr_dc }} already configured
  ansible.builtin.set_fact:
    _sonarr_dc_not_configured: "{{ _response.json | json_query(q) | length() == 0 }}"
  vars:
    q: "[?name == `{{ sonarr_dc }}`]"

- name: Set download client {{ sonarr_dc }} variables
  ansible.builtin.set_fact:
    sonarr_dc_host: "{{ sonarr_dc_host | default(sonarr_dc) }}"
    sonarr_dc_port: "{{ sonarr_dc_port | default('8082' if 'qbittorrent' in sonarr_dc else '9091') }}"
    sonarr_dc_use_ssl: "{{ sonarr_dc_use_ssl | default(true if sonarr_dc_port is defined and sonarr_dc_port == 443 else false) }}"
    sonarr_dc_username: "{{ sonarr_dc_username | default('') }}"
    sonarr_dc_password: "{{ sonarr_dc_password | default('') }}"

- name: Set common download client fields
  ansible.builtin.set_fact:
    _dc_fields:
      - name: host
        value: "{{ sonarr_dc_host }}"
      - name: port
        value: "{{ sonarr_dc_port }}"
      - name: useSsl
        value: "{{ sonarr_dc_use_ssl }}"
      - name: urlBase
        value: "{{ '' if 'qbittorrent' in sonarr_dc else '/transmission/' }}"
      - name: username
        value: "{{ sonarr_dc_username }}"
      - name: password
        value: "{{ sonarr_dc_password }}"
      - name: tvCategory
        value: "{{ sonarr_dc_category | default('series') }}"
      - name: recentTvPriority
        value: 0
      - name: olderTvPriority
        value: 0

- name: Set additional fields for qbittorrent
  ansible.builtin.set_fact:
    _dc_fields: "{{ _dc_fields + additional_fields }}"
  vars:
    additional_fields:
      - name: tvImportedCategory
      - name: initialState
        value: 0
      - name: sequentialOrder
        value: false
      - name: firstAndLast
        value: false

- name: Set additional fields for transmission
  ansible.builtin.set_fact:
    _dc_fields: "{{ _dc_fields + additional_fields }}"
  vars:
    additional_fields:
      - name: tvDirectory
      - name: addPaused
        value: false

- name: Add download client {{ sonarr_dc }} if not configured
  ansible.builtin.uri:
    url: "{{ sonarr_api_url }}/downloadclient?apiKey={{ sonarr_api_key }}"
    method: POST
    body_format: json
    body:
      enable: true
      protocol: torrent
      priority: 1
      removeCompletedDownloads: "{{ sonarr_dc_remove_completed_downloads | default(true) }}"
      removeFailedDownloads: true
      name: "{{ sonarr_dc }}"
      fields: "{{ _dc_fields }}"
      implementationName: "{{ 'qBittorrent' if 'qbittorrent' in sonarr_dc else 'Transmission' }}"
      implementation: "{{ 'QBittorrent' if 'qbittorrent' in sonarr_dc else 'Transmission' }}"
      configContract: "{{ 'QBittorrentSettings' if 'qbittorrent' in sonarr_dc else 'TransmissionSettings' }}"
      infoLink: 'https://wiki.servarr.com/sonarr/supported#{{ sonarr_dc }}'
      tags: []
    status_code: 201
  when: _sonarr_dc_not_configured
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404

- name: Default remote mapping
  ansible.builtin.set_fact:
    sonarr_dc_mapping: "{{ sonarr_dc_mapping | default('/downloads:/data/downloads') }}"

- name: Add remote mapping for download client {{ sonarr_dc }}
  ansible.builtin.uri:
    url: "{{ sonarr_api_url }}/remotepathmapping?apiKey={{ sonarr_api_key }}"
    method: POST
    body_format: json
    body:
      host: "{{ sonarr_dc }}"
      remotePath: "{{ sonarr_dc_mapping.split(':')[0] }}"
      localPath: "{{ sonarr_dc_mapping.split(':')[1] }}"
    status_code: 201
  when: _sonarr_dc_not_configured
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404
