- name: Set jackett admin password
  uri:
    url: "{{ jackett_host }}/api/v2.0/server/adminpassword"
    method: POST
    body_format: json
    body: "\"{{ jackett_password }}\""
    headers:
      Cookie: "{{ jackett_cookie }}"
    status_code: 204
    follow_redirects: yes
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404
