- name: Get jackett cookie
  ansible.builtin.uri:
    url: "{{ jackett_host }}/UI/Dashboard"
    method: GET
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404

- name: Save jackett cookie
  ansible.builtin.set_fact:
    jackett_cookie: "{{ _response.cookies_string }}"

- name: Attempt to login if jackett cookie is not present
  ansible.builtin.uri:
    url: "{{ jackett_host }}/UI/Dashboard"
    method: POST
    body_format: form-urlencoded
    body:
      password: "{{ jackett_password }}"
    status_code: 302
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404
  when: not jackett_cookie

- name: Save jackett cookie
  ansible.builtin.set_fact:
    jackett_cookie: "{{ _response.set_cookie }}"
  when: not jackett_cookie
