- name: Authenticate with admin credentials
  ansible.builtin.uri:
    url: "{{ portainer_api }}/auth"
    method: POST
    body_format: json
    body:
      username: "{{ portainer_user }}"
      password: "{{ portainer_password }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1

- name: Get Portainer JWT token
  ansible.builtin.set_fact:
    portainer_token: "{{ _response.json.jwt }}"
