- name: Check if admin user exists
  uri:
    url: "{{ portainer_api }}/users/admin/check"
    method: GET
    status_code: [ 204, 404 ]
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1

- name: Save status of admin user
  set_fact:
    portainer_admin_exists: "{{ _response.status == 204 }}"

- name: Initialize admin user
  uri:
    url: "{{ portainer_api }}/users/admin/init"
    method: POST
    body_format: json
    body:
      username: "{{ portainer_user }}"
      password: "{{ portainer_password }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1
  when: not portainer_admin_exists
