- name: Get existing endpoints
  ansible.builtin.uri:
    url: "{{ portainer_api }}/endpoints"
    method: GET
    headers:
      Authorization: "Bearer {{ portainer_token }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1

- name: Check existing local endpoint
  ansible.builtin.set_fact:
    already_exists: "{{ _response.json | json_query(query) | length() > 0 }}"
  vars:
    query: "[?contains(URL,'unix:///var/run/docker.sock')].Id"

- name: Register Portainer Agent
  ansible.builtin.uri:
    url: "{{ portainer_api }}/endpoints"
    method: POST
    body_format: form-urlencoded
    body:
      Name: "local"
      EndpointCreationType: "1"
      URL: "unix:///var/run/docker.sock"
      TLS: "false"
    headers:
      Authorization: "Bearer {{ portainer_token }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1
  when: not already_exists
