- name: Template config file
  template:
    src: ../services/cloudflared/templates/config.yml.j2
    dest: "{{ project_dir }}/cloudflared/data/config.yml"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0644'
