- name: "Get Gitea existing user(s)"
  ansible.builtin.uri:
    url: '{{ gitea_api_url }}/admin/users'
    method: GET
    status_code: 200
    force_basic_auth: true
    url_username: '{{ gitea_admin_user }}'
    url_password: '{{ gitea_admin_passwd }}'
  until: _response.status != -1 or _response.status >= 500
  register: _response

- name: "Set Gitea _user_list fact"
  ansible.builtin.set_fact:
    _user_list: "{{ _response.json | json_query('[*].login') }}"

- name: "Create users"
  include_tasks: create_user.yml
  with_items: '{{ gitea_users }}'
  vars:
    user: "{{ user }}"
  loop_control:
    loop_var: user
