- name: Set Plex config from local
  ansible.builtin.set_fact:
    overseerr_plex:
      ip: "{{ ansible_facts.default_ipv4.address }}"
      port: 32400
  when: overseerr_plex is not defined and 'plex' in services

- name: Set Plex server configuration
  ansible.builtin.uri:
    url: "{{ overseerr_api }}/settings/plex"
    method: POST
    body_format: json
    headers:
      Cookie: "connect.sid={{ overseerr_cookie }}"
    body: |
      {
        "ip": "{{ overseerr_plex.ip }}",
        "port": {{ overseerr_plex.port | default(32400) }},
        "webAppUrl": "https://app.plex.tv"
      }
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404
  when: overseerr_plex is defined

- name: Get Plex libraries
  ansible.builtin.uri:
    url: "{{ overseerr_api }}/settings/plex/library?sync=true"
    method: GET
    headers:
      Cookie: "connect.sid={{ overseerr_cookie }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404
  when: _response.changed

- name: Get all library IDs
  ansible.builtin.set_fact:
    plex_library_ids: "{{ _response.json | json_query('[*].id') }}"
  when: _response.changed

- name: Enable all Plex libraries
  ansible.builtin.uri:
    url: "{{ overseerr_api }}/settings/plex/library?enable={{ plex_library_ids | join(',') }}"
    method: GET
    headers:
      Cookie: "connect.sid={{ overseerr_cookie }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404
  when: overseerr_plex is defined and plex_library_ids is defined
