- name: Get radarr servers
  uri:
    url: "{{ overseerr_api }}/settings/radarr"
    method: GET
    headers:
      Cookie: "connect.sid={{ overseerr_cookie }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404

- name: Check for existing radarr servers with same hostname and port
  set_fact:
    existing_radarr_ids: "{{ _response.json | json_query(q) }}"
  vars:
    q: "[?hostname == `{{ overseerr_radarr.host }}` && port == `{{ overseerr_radarr.port }}`].id"

- name: Save existing radarr ID and state
  set_fact:
    existing_radarr_id: "{{ existing_radarr_ids[0] | default('') }}"
    existing_radarr: "{{ existing_radarr_ids | length() > 0 }}"

- name: Test radarr connection
  uri:
    url: "{{ overseerr_api }}/settings/radarr/test"
    method: POST
    body_format: json
    headers:
      Cookie: "connect.sid={{ overseerr_cookie }}"
    body: |
      {
        "hostname": "{{ overseerr_radarr.host }}",
        "port": {{ overseerr_radarr.port }},
        "apiKey": "{{ overseerr_radarr.api_key }}",
        "useSsl": false,
        "baseUrl": ""
      }
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404

- name: Save radarr test response
  set_fact:
    radarr_test_response: "{{ _response.json }}"

- name: Find ID of profile {{ overseerr_radarr.profile }}
  set_fact:
    radarr_profile_ids: "{{ radarr_test_response | json_query(profile_query) }}"
  vars: 
    profile_query: "profiles[?name == `{{ overseerr_radarr.profile }}`].id"

- name: Save profile id
  set_fact:
    radarr_profile_id: "{{ radarr_profile_ids[0] }}"

- name: Find ID of language profile {{ overseerr_radarr.language }}
  set_fact:
    radarr_language_profile_ids: "{{ radarr_test_response | json_query(language_profile_query) }}"
  vars: 
    language_profile_query: "profiles[?id == `{{ radarr_profile_id }}`].language.id"

- name: Save language profile id
  set_fact:
    radarr_language_profile_id: "{{ radarr_language_profile_ids[0] }}"

- name: Find radarr root folder
  set_fact:
    radarr_root_folder: "{{ _response.json.rootFolders[0].path }}"

- name: "{{ existing_radarr | ternary('Updating', 'Creating') }} radarr server configuration"
  uri:
    url: "{{ overseerr_api }}/settings/radarr/{{ existing_radarr | ternary(existing_radarr_id, '') }}"
    method: "{{ existing_radarr | ternary('PUT', 'POST') }}"
    body_format: json
    headers:
      Cookie: "connect.sid={{ overseerr_cookie }}"
    body: |
      {
        "name": "radarr",
        "hostname": "{{ overseerr_radarr.host }}",
        "port": {{ overseerr_radarr.port }},
        "apiKey": "{{ overseerr_radarr.api_key }}",
        "useSsl": false,
        "baseUrl": "",
        "activeProfileId": {{ radarr_profile_id }},
        "activeProfileName": "{{ overseerr_radarr.profile }}",
        "activeDirectory": "{{ radarr_root_folder }}",
        "is4k": false,
        "minimumAvailability": "Released",
        "isDefault": true,
        "externalUrl": "{{ overseerr_radarr.url }}",
        "syncEnabled": true,
        "preventSearch": false
      }
    status_code: "{{ existing_radarr | ternary('200', '201') }}"
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404
