---
- name: Get all categories
  ansible.builtin.uri:
    method: GET
    url: "{{ qbt_api_url }}/torrents/categories"
    headers:
      Cookie: "{{ qbit_cookie }}"
    status_code: 200
  register: get_categories_response
  retries: 10
  delay: 10
  until: get_categories_response.status > 0

- name: Update categories
  vars:
    action: "{{ 'editCategory' if category.key in get_categories_response.json.keys() else 'createCategory' }}"
  ansible.builtin.uri:
    method: POST
    url: "{{ qbt_api_url }}/torrents/{{ action }}"
    body_format: form-urlencoded
    body:
      category: "{{ category.key }}"
      savePath: /downloads/{{ category.value }}
    headers:
      Cookie: "{{ qbit_cookie }}"
    status_code: 200
  when: >
    category.key not in get_categories_response.json.keys() or
    get_categories_response.json[category.key].savePath != '/downloads/' + category.value
  with_items: "{{ qbit_categories | dict2items }}"
  loop_control:
    loop_var: category
