---
- name: Create folders for categories
  community.docker.docker_container_exec:
    container: qbittorrent
    command: "mkdir -p {{ category.key }}"
  with_items: "{{ qbittorrent_categories }}"
  loop_control:
    loop_var: category

- name: Create category in Qbittorrent
  ansible.builtin.uri:
    method: POST
    url: "{{ qbt_api_url }}/torrents/createCategory"
    body_format: form-urlencoded
    body:
      category: "{{ category.value }}"
      savePath: "{{ category.key }}"
    headers:
      Cookie: "{{ qbittorrent_cookie }}"
    status_code: 200, 409
  with_items: "{{ qbittorrent_categories }}"
  loop_control:
    loop_var: category
  register: create_category_response
  retries: 10
  delay: 10
  until: create_category_response.status > 0
