- name: Build qbittorrent config map
  vars:
    prefix: "qbit_config_"
    query: "[?starts_with(@, '{{ prefix }}')]"
  ansible.builtin.set_fact:
    qbit_config: "{{ qbit_config | default({}) | combine( { cfg.replace(prefix, ''): vars[cfg] } ) }}"
  with_items: "{{ vars.keys() | list | json_query(query) }}"
  loop_control:
    loop_var: cfg

- name: Set preferences
  vars:
    user_config:
      web_ui_username: "{{ qbit_user }}"
      web_ui_password: "{{ qbit_password }}"
  ansible.builtin.uri:
    method: POST
    url: "{{ qbt_api_url }}/app/setPreferences"
    body_format: form-urlencoded
    body:
      json: "{{ qbit_config | default({}) | combine(user_config) | to_json }}"
    headers:
      Cookie: "{{ qbit_cookie }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status > 0
