- name: Set preferences
  vars:
    user_config:
      web_ui_username: "{{ qbit_user }}"
      web_ui_password: "{{ qbit_password }}"
  ansible.builtin.uri:
    method: POST
    url: "{{ qbt_api_url }}/app/setPreferences"
    body_format: form-urlencoded
    body:
      json: "{{ qbit_config | combine(qbit_default_config) | combine(user_config) | to_json }}"
    headers:
      Cookie: "{{ qbit_cookie }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status > 0
