---
traefik_version: latest
traefik_network: apps

traefik_https: true
traefik_access_logs: false
traefik_metrics: false

traefik_acme_enabled: false
traefik_acme_staging: true
traefik_acme_email: admin@{{ domain }}
traefik_acme_provider: cloudflare
traefik_acme_env:
  CF_API_EMAIL: admin@{{ domain }}
  CF_DNS_API_TOKEN: changeme
