- name: Save services list
  set_fact:
    _services: "{{ services }}"

- name: Get status of systemd services
  service_facts:

- name: Check if systemd-resolved is enabled
  set_fact:
    resolved_running: "{{ ansible_facts.services['systemd-resolved.service'].status == 'enabled' }}"

- name: Disable SystemD stub resolver
  become: true
  import_tasks: ../tasks/systemd_no_resolved.yml
  when: resolved_running

- name: Reset services list
  set_fact:
    services: "{{ _services }}"
