- name: Update configuration for home server services

  hosts: all

  tasks:
    - name: Include vars for selected services
      include_vars: ../services/{{ item }}/vars.yml
      with_items: "{{ services }}"
      when: services

    - name: Start configuration for selected services
      include_tasks: ../services/{{ item }}/configure.yml
      with_items: "{{ services }}"
