- name: Update configuration for home server services

  hosts: all

  gather_facts: true

  tasks:
    - name: Include vars for selected services
      include_tasks: ../tasks/include_vars_if_present.yml
      vars:
        service: "{{ item }}"
      with_items: "{{ services }}"
      when: services

    - name: Start configure for selected services
      include_tasks: ../tasks/include_tasks_if_present.yml
      vars:
        service: "{{ item }}"
        task: configure
      with_items: "{{ services }}"
      when: services

