- name: Install home server services

  hosts: all

  gather_facts: yes

  pre_tasks:

    - name: Set timezone to {{ timezone }}
      timezone:
        name: "{{ timezone }}"
      become: yes

    - name: Install packages and update
      include_tasks: ../tasks/update_host.yml

    - name: Include vars for selected services
      include_tasks: ../tasks/include_vars_if_present.yml
      vars:
        service: "{{ item }}"
      with_items: "{{ services }}"
      when: services

    - name: Start preconfigure for selected services
      include_tasks: ../tasks/include_tasks_if_present.yml
      vars:
        service: "{{ item }}"
        task: preconfigure
      with_items: "{{ services }}"
      when: services

  roles:
    - name: geerlingguy.docker
      become: yes
      vars:
        docker_install_compose: false
        docker_users: "{{ ansible_facts.user_id }}"
    - name: geerlingguy.pip
      become: yes
      vars:
        pip_install_packages:
          - name: docker
          - name: docker-compose

  tasks:
    - name: Reboot host
      become: yes
      reboot:
      when: reboot_needed

    - name: Reset connection to reload user changes if not rebooted
      meta: reset_connection
      when: not reboot_needed

    - name: Setup docker networks
      include_tasks: ../tasks/setup_docker_network.yml
      vars:
        network: "{{ item }}"
      with_items: "{{ networks }}"
      when: networks

    - name: Setup docker volumes
      include_tasks: ../tasks/create_volume.yml
      vars:
        volume: "{{ item }}"
      with_items: "{{ volumes }}"
      when: volumes

    - name: Start install for selected services
      include_tasks: ../tasks/include_tasks_if_present.yml
      vars:
        service: "{{ item }}"
        task: install
      with_items: "{{ services }}"
      when: services

    - name: Start configure for selected services
      include_tasks: ../tasks/include_tasks_if_present.yml
      vars:
        service: "{{ item }}"
        task: configure
      with_items: "{{ services }}"
      when: services
