- name: Install home server services

  hosts: all

  pre_tasks:

    - name: Set timezone to {{ timezone }}
      timezone:
        name: "{{ timezone }}"
      become: yes

    - name: Install packages and update
      include_tasks: ../tasks/update_host.yml

    - name: Enable wireguard module
      include_tasks: ../tasks/enable_kernel_module.yml
      vars:
        module: wireguard
      when: '"wireguard" in services'

  roles:
    - name: geerlingguy.docker
      become: yes
      vars:
        docker_install_compose: false
        docker_users: "{{ ansible_facts.user_id }}"
    - name: geerlingguy.pip
      become: yes
      vars:
        pip_install_packages:
          - name: docker
          - name: docker-compose

  tasks:
    - name: Reboot host
      become: yes
      reboot:
      when: reboot_needed

    - name: Reset connection to reload user changes if not rebooted
      meta: reset_connection
      when: not reboot_needed

    - name: Setup docker networks
      include_tasks: ../tasks/setup_docker_network.yml
      vars:
        network: "{{ item }}"
      with_items: "{{ networks }}"
      when: networks

    - name: Setup docker volumes
      include_tasks: ../tasks/create_volume.yml
      vars:
        volume: "{{ item }}"
      with_items: "{{ volumes }}"
      when: volumes

    - name: Include vars for selected services
      include_vars: ../services/{{ item }}/vars.yml
      with_items: "{{ services }}"
      when: services

    - name: Start install for selected services
      include_tasks: ../services/{{ item }}/install.yml
      with_items: "{{ services }}"
      when: services

    - name: Start configuration for selected services
      include_tasks: ../services/{{ item }}/configure.yml
      with_items: "{{ services }}"
      when: services
