---
- name: Setup apps using docker

  hosts: home

  roles:
    - role: base/docker
      tags: docker
    - role: base/docker_compose
      tags: docker

  tasks:
    - name: Include apps
      ansible.builtin.include_role:
        name: "apps/{{ app }}"
        apply:
          tags:
            - "{{ app }}"
      with_items: "{{ apps }}"
      loop_control:
        loop_var: app
      tags:
        - always
