- name: Update home server services

  hosts: all

  gather_facts: true

  pre_tasks:
    - name: Include vars for selected services
      include_tasks: ../tasks/include_vars_if_present.yml
      vars:
        service: "{{ item }}"
      with_items: "{{ services }}"
      when: services

    - name: Include group-specific vars for selected services
      include_tasks: ../tasks/include_vars_if_present.yml
      vars:
        service: "{{ item[1] }}"
        file: "{{ item[0] }}"
      loop: "{{ group_names | difference(['ungrouped']) | product(services) }}"
      when: services

    - name: Include host-specific vars for selected services
      include_tasks: ../tasks/include_vars_if_present.yml
      vars:
        service: "{{ item }}"
        file: "{{ inventory_hostname }}"
      with_items: "{{ services }}"
      when: services

  tasks:
    - name: Default networks
      ansible.builtin.set_fact:
        networks: "{{ networks | default(['main']) }}"

    - name: Setup docker networks
      include_tasks: ../tasks/setup_docker_network.yml
      vars:
        network: "{{ item }}"
      with_items: "{{ networks }}"

    - name: Setup docker volumes
      include_tasks: ../tasks/create_volume.yml
      vars:
        volume: "{{ item }}"
      with_items: "{{ volumes }}"
      when: volumes is defined and volumes | length > 0

    - name: Start install for selected services
      include_tasks: ../tasks/include_tasks_if_present.yml
      vars:
        service: "{{ item }}"
        task: install
      with_items: "{{ services }}"
      when: services

    - name: Start configure for selected services
      include_tasks: ../tasks/include_tasks_if_present.yml
      vars:
        service: "{{ item }}"
        task: configure
      with_items: "{{ services }}"
      when: services
