---
- name: Include host specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files: [ "{{ ansible_hostname }}.yml" ]
      skip: true

- name: Create directory structure
  ansible.builtin.import_role: name=common tasks_from=service_dir_structure
  vars:
    subdirs:
      - vaultwarden
      - vaultwarden/data

- name: Template compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ project_dir }}/vaultwarden/compose.yml"
    owner: "{{ ansible_facts.user_uid }}"
    group: "{{ ansible_facts.user_gid }}"
    mode: 0600

- name: Setup docker network {{ vaultwarden_network }}
  community.docker.docker_network:
    name: "{{ vaultwarden_network }}"

- name: Start service using docker compose
  community.docker.docker_compose:
    project_name: vaultwarden
    project_src: "{{ project_dir }}/vaultwarden"
    pull: true
    remove_orphans: true
