- name: Set preferences in QBittorrent
  uri:
    url: "{{ qbt_api_url }}/app/setPreferences"
    method: POST
    body_format: form-urlencoded
    body:
      json: "{{ qbt_config | to_json }}"
    headers:
      Cookie: "{{ qbt_cookie }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404
