- name: Get VueTorrent in temp folder
  git:
    repo: https://github.com/WDaan/VueTorrent.git
    dest: "~/vuetorrent"
    version: latest-release

- name: Copy VueTorrent to Qbittorrent volume
  shell: "docker cp ~/vuetorrent qbittorrent:/config/vuetorrent"

- name: Delete VueTorrent temp folder
  file:
    state: absent
    path: ~/vuetorrent

- name: Create QBittorrent preferences request body
  set_fact:
    qbt_pref:
      alternative_webui_enabled: true
      alternative_webui_path: "/config/vuetorrent"

- name: Enable Alternative Web UI in Qbittorrent
  uri:
    url: "{{ qbt_api_url }}/app/setPreferences"
    method: POST
    body_format: form-urlencoded
    body:
      json: "{{ qbt_pref | to_json }}"
    headers:
      Cookie: "{{ qbt_cookie }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404