- name: Get VueTorrent in temp folder
  ansible.builtin.git:
    repo: https://github.com/WDaan/VueTorrent.git
    dest: "{{ project_dir }}/qbittorrent/data/vuetorrent"
    version: latest-release

- name: Create QBittorrent preferences request body
  ansible.builtin.set_fact:
    qbt_pref:
      alternative_webui_enabled: true
      alternative_webui_path: "/config/vuetorrent"

- name: Enable Alternative Web UI in Qbittorrent
  ansible.builtin.uri:
    url: "{{ qbt_api_url }}/app/setPreferences"
    method: POST
    body_format: form-urlencoded
    body:
      json: "{{ qbt_pref | to_json }}"
    headers:
      Cookie: "{{ qbt_cookie }}"
    status_code: 200
  register: _response
  retries: 10
  delay: 10
  until: _response.status != -1 and _response.status < 500 and _response.status != 404
