---
- name: Create directory structure
  ansible.builtin.import_role: name=common tasks_from=service_dir_structure
  vars:
    subdirs:
      - portainer_agent
      - portainer_agent/data

- name: Template compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ project_dir }}/portainer_agent/compose.yml"
    owner: "{{ ansible_facts.user_uid }}"
    group: "{{ ansible_facts.user_gid }}"
    mode: 0644

- name: Setup docker network {{ portainer_agent_network }}
  community.docker.docker_network:
    name: "{{ portainer_agent_network }}"

- name: Start service using docker compose
  community.docker.docker_compose:
    project_name: portainer_agent
    project_src: "{{ project_dir }}/portainer_agent"
    pull: true
    remove_orphans: true
